version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
        fingerprints:
          - '23:4e:9e:31:b7:9e:f8:e8:c5:7d:c7:81:1d:f1:45:f0'
      - checkout
      - restore_cache:
          keys:
            - dependencies_demo
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_demo
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          # shell chmod +x  赋予执行权限
          # 执行 shell 脚本
          command: chmod +x scripts/deploy.shell
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh
